# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cfcalls.protocols import models_pb2 as cfcalls_dot_protocols_dot_models__pb2
from cfcalls.protocols import signal_pb2 as cfcalls_dot_protocols_dot_signal__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cfcalls/protocols/signal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignalServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPublisher = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/SetPublisher',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.SetPublisherRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.SetPublisherResponse.FromString,
                _registered_method=True)
        self.SendAnswer = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/SendAnswer',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.SendAnswerRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.SendAnswerResponse.FromString,
                _registered_method=True)
        self.IceTrickle = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/IceTrickle',
                request_serializer=cfcalls_dot_protocols_dot_models__pb2.ICETrickle.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.ICETrickleResponse.FromString,
                _registered_method=True)
        self.UpdateSubscriptions = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/UpdateSubscriptions',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateSubscriptionsRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateSubscriptionsResponse.FromString,
                _registered_method=True)
        self.UpdateMuteStates = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/UpdateMuteStates',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateMuteStatesRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateMuteStatesResponse.FromString,
                _registered_method=True)
        self.IceRestart = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/IceRestart',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.ICERestartRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.ICERestartResponse.FromString,
                _registered_method=True)
        self.SendStats = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/SendStats',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.SendStatsRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.SendStatsResponse.FromString,
                _registered_method=True)
        self.StartNoiseCancellation = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/StartNoiseCancellation',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.StartNoiseCancellationRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.StartNoiseCancellationResponse.FromString,
                _registered_method=True)
        self.StopNoiseCancellation = channel.unary_unary(
                '/cfcalls.protocols.signal.SignalServer/StopNoiseCancellation',
                request_serializer=cfcalls_dot_protocols_dot_signal__pb2.StopNoiseCancellationRequest.SerializeToString,
                response_deserializer=cfcalls_dot_protocols_dot_signal__pb2.StopNoiseCancellationResponse.FromString,
                _registered_method=True)


class SignalServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetPublisher(self, request, context):
        """SetPublisher sends the WebRTC offer for the peer connection used to publish A/V
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAnswer(self, request, context):
        """answer is sent by the client to the SFU after receiving a subscriber_offer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IceTrickle(self, request, context):
        """SendICECandidate sends an ICE candidate to the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSubscriptions(self, request, context):
        """UpdateSubscribers is used to notify the SFU about the list of video subscriptions
        TODO: sync subscriptions based on this + update tracks using the dimension info sent by the user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMuteStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IceRestart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartNoiseCancellation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopNoiseCancellation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPublisher': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPublisher,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.SetPublisherRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.SetPublisherResponse.SerializeToString,
            ),
            'SendAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAnswer,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.SendAnswerRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.SendAnswerResponse.SerializeToString,
            ),
            'IceTrickle': grpc.unary_unary_rpc_method_handler(
                    servicer.IceTrickle,
                    request_deserializer=cfcalls_dot_protocols_dot_models__pb2.ICETrickle.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.ICETrickleResponse.SerializeToString,
            ),
            'UpdateSubscriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSubscriptions,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateSubscriptionsRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateSubscriptionsResponse.SerializeToString,
            ),
            'UpdateMuteStates': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMuteStates,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateMuteStatesRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.UpdateMuteStatesResponse.SerializeToString,
            ),
            'IceRestart': grpc.unary_unary_rpc_method_handler(
                    servicer.IceRestart,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.ICERestartRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.ICERestartResponse.SerializeToString,
            ),
            'SendStats': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStats,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.SendStatsRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.SendStatsResponse.SerializeToString,
            ),
            'StartNoiseCancellation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartNoiseCancellation,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.StartNoiseCancellationRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.StartNoiseCancellationResponse.SerializeToString,
            ),
            'StopNoiseCancellation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopNoiseCancellation,
                    request_deserializer=cfcalls_dot_protocols_dot_signal__pb2.StopNoiseCancellationRequest.FromString,
                    response_serializer=cfcalls_dot_protocols_dot_signal__pb2.StopNoiseCancellationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cfcalls.protocols.signal.SignalServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cfcalls.protocols.signal.SignalServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignalServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetPublisher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/SetPublisher',
            cfcalls_dot_protocols_dot_signal__pb2.SetPublisherRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.SetPublisherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/SendAnswer',
            cfcalls_dot_protocols_dot_signal__pb2.SendAnswerRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.SendAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IceTrickle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/IceTrickle',
            cfcalls_dot_protocols_dot_models__pb2.ICETrickle.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.ICETrickleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSubscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/UpdateSubscriptions',
            cfcalls_dot_protocols_dot_signal__pb2.UpdateSubscriptionsRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.UpdateSubscriptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMuteStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/UpdateMuteStates',
            cfcalls_dot_protocols_dot_signal__pb2.UpdateMuteStatesRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.UpdateMuteStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IceRestart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/IceRestart',
            cfcalls_dot_protocols_dot_signal__pb2.ICERestartRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.ICERestartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/SendStats',
            cfcalls_dot_protocols_dot_signal__pb2.SendStatsRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.SendStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartNoiseCancellation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/StartNoiseCancellation',
            cfcalls_dot_protocols_dot_signal__pb2.StartNoiseCancellationRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.StartNoiseCancellationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopNoiseCancellation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cfcalls.protocols.signal.SignalServer/StopNoiseCancellation',
            cfcalls_dot_protocols_dot_signal__pb2.StopNoiseCancellationRequest.SerializeToString,
            cfcalls_dot_protocols_dot_signal__pb2.StopNoiseCancellationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
